package com.medical.med.exeption;

public enum Code {

    VALIDATION_SURNAME,
    VALIDATION_NAME,
    VALIDATION_DATE_OF_BIRTH,
    VALIDATION_SEX,
    VALIDATION_PHONE_NUMBER,
    VALIDATION_EMAIL,
    VALIDATION_SNILS,
    VALIDATION_SINGLE_POLICY_NUMBER,

    INVALID_PARAMETER,
    MISSING_PARAMETER,
    INVALID_JSON,
    INVALID_DATE_FORMAT,
    RESOURCE_NOT_FOUND,

    DUPLICATE_EMAIL,
    DUPLICATE_PHONE,
    DUPLICATE_SNILS,
    DUPLICATE_POLICY_NUMBER,

    INTERNAL_SERVER_ERROR
}
